### ISSUE TITLE
Please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [AshuTyagi16/Launcher-OnePlus#1]
Could you please remember to increase `versionCode` with each updated APK you provide? That's still set to `1` as it was for the past 19 versions. Without that being increased, Android doesn't consider newer versions to be updates, and thus doesn't offer to update them. Thanks!

PS: while `versionName` is just for humans to read, it could not hurt to "increase" that as well :wink:

**Comment by AshuTyagi16** [comment]
@IzzySoft Sure. I'll keep that in mind for future releases. Thanks.

**Comment by IzzySoft** [comment]
Thanks a lot!

**Comment by IzzySoft** [comment]
PS: would you consider [tagging your releases](https://github.com/AshuTyagi16/Launcher-OnePlus/releases) and attaching the APK to its corresponding tag? Multiple advantages with that:

* easier to find
* easier to identify the version (and whether its newer than what one already has)
* the binaries don't "bloat" your repo

**Comment by IzzySoft** [comment]
Just wondering: You've made a new release 2 days ago – but `build.gradle` still shows versionName "1.0" and versionCode "1", while the tag is named "0.0.1"? That way users will never see updates (see initial comment).
